-- SQL file for the app

CREATE TABLE account (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	handle TEXT NOT NULL,
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	password TEXT
);

CREATE TABLE entry (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author_id BIGINT REFERENCES account(id) NOT NULL
);

CREATE TABLE entry_closures (
	ancestor BIGINT REFERENCES entry(id) NOT NULL,
	descendant BIGINT REFERENCES entry(id) NOT NULL,
	depth INT NOT NULL
);